-- Production audio and lipsync catalogue. These rows are visible to the agent only
-- when their provider credentials are configured by Settings.provider_is_configured.

insert into public.gen_models (
  id, family, provider, modality, label, description_llm,
  min_duration_s, max_duration_s, resolutions, aspects,
  supports_i2v, supports_last_frame, supports_char_ref, supports_audio,
  capabilities, cost_per_second, cost_per_image, credits_per_unit,
  min_plan, status, sort
) values
  ('eleven-v3-voice', 'ElevenLabs', 'elevenlabs', 'audio', 'Eleven v3 Voice',
   'Expressive single-speaker speech with performance direction and inline audio tags.',
   0.5, 300, '{}', '{}', false, false, false, true,
   array['voice','performance_direction','audio_tags'], 0.0010, null, 1, 'free', 'active', 10),
  ('eleven-v3-dialogue', 'ElevenLabs', 'elevenlabs', 'audio', 'Eleven v3 Dialogue',
   'Multi-speaker dialogue in one coherent take; preserves timing and interaction better than stitching lines.',
   0.5, 300, '{}', '{}', false, false, false, true,
   array['dialogue','multi_speaker','performance_direction','audio_tags'], 0.0012, null, 1, 'pro', 'active', 20),
  ('eleven-multilingual-v2', 'ElevenLabs', 'elevenlabs', 'audio', 'Eleven Multilingual v2',
   'Stable multilingual narration and character voice-over.',
   0.5, 300, '{}', '{}', false, false, false, true,
   array['voice','multilingual'], 0.0010, null, 1, 'free', 'active', 30),
  ('eleven-music-v2', 'ElevenLabs', 'elevenlabs', 'audio', 'Eleven Music',
   'Prompted or section-planned music with exact duration and structured composition control.',
   3, 300, '{}', '{}', false, false, false, true,
   array['music','composition_plan','sections','instrumental'], 0.0100, null, 2, 'pro', 'active', 40),
  ('eleven-sfx-v2', 'ElevenLabs', 'elevenlabs', 'audio', 'Eleven Sound Effects',
   'Sound effects, transitions and loopable ambience generated from a precise description.',
   0.5, 30, '{}', '{}', false, false, false, true,
   array['sfx','ambience','loop'], 0.0100, null, 2, 'free', 'active', 50),
  ('lipsync-2', 'Sync Labs', 'sync', 'lipsync', 'Lipsync 2',
   'General-purpose lip synchronization for clear frontal or three-quarter faces.',
   1, 300, '{}', '{}', true, false, true, true,
   array['lipsync','segments','active_speaker_detection'], 0.0500, null, 8, 'pro', 'active', 10),
  ('lipsync-2-pro', 'Sync Labs', 'sync', 'lipsync', 'Lipsync 2 Pro',
   'Higher-detail lip synchronization for hero dialogue and difficult facial motion.',
   1, 300, '{}', '{}', true, false, true, true,
   array['lipsync','segments','multi_speaker','active_speaker_detection'], 0.0830, null, 14, 'business', 'active', 20),
  ('sync-3', 'Sync Labs', 'sync', 'lipsync', 'Sync 3',
   'Production lipsync for occlusions, extreme angles and high-resolution delivery.',
   1, 300, '{}', '{}', true, false, true, true,
   array['lipsync','segments','multi_speaker','active_speaker_detection','occlusion','4k'], 0.1330, null, 22, 'business', 'active', 30)
on conflict (id) do update set
  family = excluded.family,
  provider = excluded.provider,
  modality = excluded.modality,
  label = excluded.label,
  description_llm = excluded.description_llm,
  min_duration_s = excluded.min_duration_s,
  max_duration_s = excluded.max_duration_s,
  supports_i2v = excluded.supports_i2v,
  supports_char_ref = excluded.supports_char_ref,
  supports_audio = excluded.supports_audio,
  capabilities = excluded.capabilities,
  cost_per_second = excluded.cost_per_second,
  credits_per_unit = excluded.credits_per_unit,
  min_plan = excluded.min_plan,
  status = excluded.status,
  sort = excluded.sort,
  updated_at = now();
